Update configuration files with new versions

diff --git a/config/etc/rc b/config/etc/rc
--- a/config/etc/rc
+++ b/config/etc/rc
@@ -1,4 +1,4 @@
-#	$OpenBSD: rc,v 1.564 2022/08/29 11:51:05 deraadt Exp $
+#	$OpenBSD: rc,v 1.570 2023/01/25 10:53:15 asou Exp $
 
 # System startup script run by init on autoboot or after single-user.
 # Output and error are redirected to console by init, and the console is the
@@ -188,12 +188,12 @@ reorder_libs() {
 		fi
 	done
 
-	echo -n 'reordering libraries:'
+	echo 'reordering:'
 
 	# Remount the (read-only) filesystems in _ro_list as read-write.
 	for _mp in $_ro_list; do
 		if ! mount -u -w $_mp; then
-			echo ' failed.'
+			echo '(failed).'
 			return
 		fi
 	done
@@ -215,6 +215,7 @@ reorder_libs() {
 		cd $_tmpdir
 		ar x $_liba
 		if [[ $_lib == ld.so ]]; then
+			echo " $_lib"
 			args="-g -x -e _dl_start \
 			    --version-script=Symbols.map --shared -Bsymbolic \
 			    --no-undefined"
@@ -225,12 +226,28 @@ reorder_libs() {
 			$_install /usr/libexec/ld.so /usr/libexec/ld.so.save
 			$_install ld.so.test $_lib_dir/ld.so
 		else
+			echo " ${_lib%%.*}"
 			cc -shared -o $_lib $(ls *.so | sort -R) $(<.ldadd)
 			[[ -s $_lib ]] && file $_lib | fgrep -q 'shared object'
 			LD_BIND_NOW=1 LD_LIBRARY_PATH=$_tmpdir awk 'BEGIN {exit 0}'
 			LD_BIND_NOW=1 LD_LIBRARY_PATH=$_tmpdir openssl \
 			    x509 -in /etc/ssl/cert.pem -out /dev/null
 			$_install $_lib $_lib_dir/$_lib
+		fi
+		) || { _error=true; break; }
+	done
+
+	for _bin in $_relink/usr/sbin/sshd; do
+		_tmpdir=$(mktemp -dq $_relink/_rebuild.XXXXXXXXXXXX) &&
+		(
+		set -o errexit
+		cd $_tmpdir
+		_binn=${_bin##*/}
+		_bint=${_bin}/${_binn}.tar
+		if [[ -f $_bint ]]; then
+			echo " $_binn"
+			tar xf $_bint
+			make -f Makefile.relink relink >/dev/null 2>&1
 		fi
 		) || { _error=true; break; }
 	done
@@ -243,10 +260,22 @@ reorder_libs() {
 	done
 
 	if $_error; then
-		echo ' failed.'
+		echo '(failed).'
 	else
-		echo ' done.'
+		echo '.'
 	fi
+}
+
+# Read output of reorder_libs co-process and output on console.
+wait_reorder_libs() {
+	local _line
+
+	[[ $library_aslr == NO ]] && return
+
+	while IFS= read -p _line; do
+		echo -n "$_line"
+	done
+	echo
 }
 
 # Run rc.* script and email output to root.
@@ -495,6 +524,8 @@ mount -s /var >/dev/null 2>&1		# cannot be on NFS
 mount -s /var/log >/dev/null 2>&1	# cannot be on NFS
 mount -s /usr >/dev/null 2>&1		# if NFS, fstab must use IP address
 
+reorder_libs 2>&1 |&
+
 start_daemon slaacd dhcpleased resolvd >/dev/null 2>&1
 
 echo 'starting network'
@@ -509,7 +540,7 @@ start_daemon unwind >/dev/null 2>&1
 
 random_seed
 
-reorder_libs
+wait_reorder_libs
 
 # Clean up left-over files.
 rm -f /etc/nologin /var/spool/lock/LCK.*
